information:
  province: 
  city: 
  company: 
  manager: 
  tester: 
  substation: 
  location: 
  saveVideoPath: ./video
  saveImagePath: ./image
cells:
- name: cell0
  devices:
  - category: IrCamera
    model: VirtualIrDevice
    version: 1.0
    serialNumber: 
    irCameraDeviceParameters:
      ip: 
      width: 160
      stride: 160
      height: 120
      bpp: 4
      videoFrameRate: 30
      temperatureFrameRate: 1
      emissivity: 
      reflectedTemperature: 
      transmission: 
      atmosphericTemperature: 
      relativeHumidity: 
      distance: 
    cameraDeviceParameters: 
